//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDB.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BehaviorIOADetail
    {
        public int BehaviorIOAId { get; set; }
        public Nullable<int> MeasurementId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string ActiveInd { get; set; }
        public Nullable<int> FrequencyCount { get; set; }
        public string Duration { get; set; }
        public Nullable<int> NormalBehaviorId { get; set; }
        public string IOAPerc { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> YesOrNo { get; set; }
        public Nullable<int> ObserverId { get; set; }
        public Nullable<System.DateTime> TimeOfEvent { get; set; }
    
        public virtual BehaviorIOADetail BehaviorIOADetails1 { get; set; }
        public virtual BehaviorIOADetail BehaviorIOADetail1 { get; set; }
    }
}
